---
title: "Stimulation study"
author: "Thuy Nguyen"
date: "5/17/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
set.seed(124)
library(tidyverse)
lin <- function(x) 2*x
sin_2pi <- function(x) sin(2*pi*x)
sin_30 <- function(x) sin(30*x)

simulate <- function(n, func){
  # Sampling x and epsilon
  x<- sort(runif(n))
  eps <- rnorm(n)
  
  # calculate y
  y <- func(x)+eps
  
  # fit  linear and global polynomial models
  y1 <- lm(y ~ x)$fitted.values
  y2<- lm(y ~ poly(x,2))$fitted.values
  y3<- lm(y ~ poly(x,3))$fitted.values
  y4<- lm(y ~ poly(x,4))$fitted.values
  y5<- lm(y ~ poly(x,5))$fitted.values
  
  # fit local polynomial models
  y_L0 <- predict(loess(y~ x, degree = 0))
  y_L1 <- predict(loess(y~ x, degree = 1))
  y_L2 <- predict(loess(y~ x, degree = 2))
 
  #choice of bandwidth
  h <- 0.5* n^(-1/3)
  
  # fit NW estimators with box and Gaussian kernels
  ybox <- ksmooth(x,y, kernel = "box", bandwidth = h)$y
  
  y_gauss <- ksmooth(x,y, kernel ="normal", bandwidth = h)$y
  
  # calculate and format MSE
  mse <- colMeans( (cbind(y1,y1,y2,y4,y5,y_L0,y_L1, y_L2, ybox, y_gauss)- func(x))^2)
  names(mse) <- c("Linear", paste("Poly Deg:", 2:5),paste("Local Poly Deg:", 0:2), "NW_box", "NW-Gaussian")
  mse
  
}
```

```{r}
mse_500_lin <- colMeans(matrix(replicate(500, simulate(500, lin)), ncol = 10, byrow = TRUE)) 
names(mse_500_lin) <- c("Linear", paste("Poly Deg:", 2:5),paste("Local Poly Deg:", 0:2), "NW_box","NW-Gaussian") 
 
mse_500_sin2pi <- colMeans(matrix(replicate(500, simulate(500, sin_2pi)), ncol = 10, byrow = TRUE)) 
names(mse_500_sin2pi) <- c("Linear", paste("Poly Deg:", 2:5),paste("Local Poly Deg:", 0:2), "NW-Box","NW-Gaussian") 
 
mse_500_sin30 <- colMeans(matrix(replicate(500, simulate(500, sin_30)), ncol = 10, byrow = TRUE)) 
names(mse_500_sin30) <- c("Linear", paste("Poly Deg:", 2:5),paste("Local Poly Deg:", 0:2), "NW-Box","NW-Gaussian") 
 
mse_1000_lin <- colMeans(matrix(replicate(500, simulate(1000, lin)), ncol = 10, byrow = TRUE)) 
names(mse_1000_lin) <- c("Linear", paste("Poly Deg:", 2:5),paste("Local Poly Deg:", 0:2), "NW-Box","NW-Gaussian") 
 
mse_1000_sin2pi <- colMeans(matrix(replicate(500, simulate(1000, sin_2pi)), ncol = 10, byrow = TRUE)) 
names(mse_1000_sin2pi) <- c("Linear", paste("Poly Deg:", 2:5),paste("Local Poly Deg:", 0:2), "NW-Box","NW-Gaussian") 
 
mse_1000_sin30 <- colMeans(matrix(replicate(500, simulate(1000, sin_30)), ncol = 10, byrow = TRUE)) 
names(mse_1000_sin30) <- c("Linear", paste("Poly Deg:", 2:5),paste("Local Poly Deg:", 0:2), "NW-Box","NW-Gaussian") 
 
mse_2000_lin <- colMeans(matrix(replicate(500, simulate(2000, lin)), ncol = 10, byrow = TRUE)) 
names(mse_2000_lin) <- c("Linear", paste("Poly Deg:", 2:5),paste("Local Poly Deg:",0:2), "NW-Box","NW-Gaussian") 
 
mse_2000_sin2pi <- colMeans(matrix(replicate(500, simulate(2000, sin_2pi)), ncol = 10, byrow = TRUE)) 
names(mse_2000_sin2pi) <- c("Linear", paste("Poly Deg:", 2:5),paste("Local Poly Deg:", 0:2), "NW-Box","NW-Gaussian") 
 
mse_2000_sin30 <- colMeans(matrix(replicate(500, simulate(2000, sin_30)), ncol = 10, byrow = TRUE)) 
names(mse_2000_sin30) <- c("Linear", paste("Poly Deg:", 2:5),paste("Local Poly Deg:", 0:2), "NW-Box","NW-Gaussian")
```

```{r}
data_lin <- as.data.frame(rbind(mse_500_lin, mse_1000_lin, mse_2000_lin)) 
data_lin$n <- c(500, 1000, 2000) 
data_lin <- gather(data_lin, "Model", "MSE", "Linear":"NW-Gaussian", factor_key=TRUE) 
ggplot(data_lin,aes(x=n, y = MSE, color = Model)) + geom_point() + geom_line()
```